run_name: Qwen7B_warmup_emcot_dpo_1
output_dir: /shared/storage-01/jiarui14/EM-CoT/EM-CoT/outputs/Qwen7B_warmup_emcot_dpo_1
model_name_or_path: /shared/storage-01/jiarui14/EM-CoT/EM-CoT/outputs/Qwen7B_cold_start_orig_eos
ref_model: /shared/storage-01/jiarui14/EM-CoT/EM-CoT/outputs/Qwen7B_cold_start_orig_eos
learning_rate: 5.0e-7
num_train_epochs: 2
logging_steps: 1
gradient_checkpointing: true
do_train: true
do_eval: true
eval_steps: 10000
loss_type: sigmoid
lr_scheduler_type: cosine
max_length: 4096
max_prompt_length: 1000
eval_strategy: steps
bf16: true
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 8
report_to: wandb
label_smoothing: 0.1
eot_token: <|im_end|>
sanity_check: false
num_collect_files: 4
iter: 1
model_prefix: Qwen7B-warmup
base_model: Qwen/Qwen2.5-Math-7B