run_name: Qwen_numina_iter1
output_dir: Qwen_numina_iter1
model_name_or_path: Qwen/Qwen2.5-Math-7B
ref_model: Qwen/Qwen2.5-Math-7B
learning_rate: 5.0e-7
num_train_epochs: 2
logging_steps: 2
gradient_checkpointing: true
do_train: true
do_eval: true
eval_steps: 10000
choose_type: max_min
train_dir: ./iter_dpo_numina_rule_reward/Train1_Qwen_numina_iter1_reward.json
eval_dir: ./iter_dpo_numina_rule_reward/Train1_Qwen_numina_iter1_reward.json
loss_type: sigmoid
lr_scheduler_type: cosine
max_length: 4096
max_prompt_length: 1000
eval_strategy: steps
bf16: true
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 16
report_to: wandb
label_smoothing: 0.1
eot_token: <|im_end|>
